pipeline {

    agent any

    stages {
        stage('Build Image') {
            steps {
                dir('db') {
                    sh "docker build -t catalogue-db-image ."
                }
            }
        }
        stage('Tag Image') {
            steps {
                sh "docker tag catalogue-db-image roboshop0088.azurecr.io/catalogue-db-image:latest"
            }
        }
        stage('Push Image') {
            steps {
                sh "docker push roboshop0088.azurecr.io/catalogue-db-image"
            }
        }
    }
}
